In [1]:
#a) Install the "readxl" package using the appropriate R function.
install.packages("readxl")
library(readxl)
install.packages("tidyverse")
library(tidyverse)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [2]:
install.packages(c("tidyverse", "nycflights13"))
library(tidyverse)
library(nycflights13)

Installing packages into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

In [14]:
# Task: Find all flights operated by United Airlines (carrier code: "UA")

united_flights <- flights %>%
  select(year, month, day, dep_delay, arr_delay, carrier, flight) %>%
  filter(carrier == "UA") %>%
  head(10)

united_flights

   year month day dep_delay arr_delay carrier
1  2013 1     1    2         11       UA
2  2013 1     1    4         20       UA
3  2013 1     1   -4         12       UA
4  2013 1     1   -2          7       UA
5  2013 1     1   -2        -14       UA
6  2013 1     1   -1         -8       UA
7  2013 1     1    0        -17       UA
8  2013 1     1   11         14       UA
9  2013 1     1   -4          1       UA
10 2013 1     1   -2         29       UA

In [3]:

head(nycflights13::flights)

  year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1 2013 1     1   517      515             2         830      819
2 2013 1     1   533      529             4         850      830
3 2013 1     1   542      540             2         923      850
4 2013 1     1   544      545            -1        1004     1022
5 2013 1     1   554      600            -6         812      837
6 2013 1     1   554      558            -4         740      728
  arr_delay carrier flight tailnum origin dest air_time distance hour minute
1  11       UA      1545   N14228  EWR    IAH  227      1400     5    15
2  20       UA      1714   N24211  LGA    IAH  227      1416     5    29
3  33       AA      1141   N619AA  JFK    MIA  160      1089     5    40
4 -18       B6       725   N804JB  JFK    BQN  183      1576     5    45
5 -25       DL       461   N668DN  LGA    ATL  116       762     6     0
6  12       UA      1696   N39463  EWR    ORD  150       719     5    58
  time_hour
1 2013-01-01 05:00:00
2 2013-01-01 05:00:00
3 2013-01-01 05:00:00
4 2013-01-01 05:00:00
5 2013-01-01 06:00:00
6 2013-01-01 05:00:00

In [32]:

#1st one
flight <- flights %>% select(year, month, day, flight, origin, dest, arr_delay, carrier)
united_flights <- flight %>%
  filter(carrier == "UA")
print("Solution for Exercise 1:")
head(united_flights, 10)

[1] "Solution for Exercise 1:"

   year month day flight origin dest arr_delay carrier
1  2013 1     1   1545   EWR    IAH   11       UA
2  2013 1     1   1714   LGA    IAH   20       UA
3  2013 1     1   1696   EWR    ORD   12       UA
4  2013 1     1    194   JFK    LAX    7       UA
5  2013 1     1   1124   EWR    SFO  -14       UA
6  2013 1     1   1187   EWR    LAS   -8       UA
7  2013 1     1   1077   EWR    MIA  -17       UA
8  2013 1     1    303   JFK    SFO   14       UA
9  2013 1     1    496   LGA    IAH    1       UA
10 2013 1     1   1665   EWR    LAX   29       UA

In [33]:

# 2nd one
busiest_routes <- flights %>%
  group_by(origin, dest) %>%
  summarize(num_flights = n()) %>%
  arrange(desc(num_flights)) %>%
  filter(num_flights >= 1000)

print("Solution for Exercise 2:")
busiest_routes

`summarise()` has grouped output by 'origin'. You can override using the
`.groups` argument.

[1] "Solution for Exercise 2:"

   origin dest num_flights
1  JFK    LAX  11262
2  LGA    ATL  10263
3  LGA    ORD   8857
4  JFK    SFO   8204
5  LGA    CLT   6168
6  EWR    ORD   6100
7  JFK    BOS   5898
8  LGA    MIA   5781
9  JFK    MCO   5464
10 EWR    BOS   5327
11 EWR    SFO   5127
12 LGA    DTW   5040
13 EWR    CLT   5026
14 EWR    ATL   5022
15 EWR    MCO   4941
16 EWR    LAX   4912
17 LGA    DFW   4858
18 JFK    SJU   4752
19 LGA    DCA   4716
20 LGA    BOS   4283
21 JFK    FLL   4254
22 LGA    FLL   4008
23 JFK    LAS   3987
24 EWR    IAH   3973
25 EWR    FLL   3793
26 LGA    MSP   3713
27 LGA    DEN   3704
28 LGA    MCO   3677
29 JFK    BUF   3582
30 LGA    RDU   3581
⋮  ⋮      ⋮    ⋮
68 JFK    ROC  1679
69 EWR    RIC  1667
70 JFK    MSY  1633
71 JFK    SAN  1603
72 LGA    MKE  1525
73 EWR    RDU  1482
74 JFK    AUS  1471
75 EWR    RSW  1437
76 EWR    CHS  1424
77 JFK    BTV  1364
78 EWR    MCI  1356
79 JFK    RSW  1339
80 JFK    SYR  1311
81 JFK    PWM  1304
82 EWR    IND  1301
83 JFK    JAX  1299
84 JFK    PIT  1249
85 EWR    JAX  1242
86 EWR    IAD  1236
87 JFK    BWI  1221
88 JFK    DTW  1166
89 EWR    MSY  1155
90 EWR    DAY  1134
91 EWR    SAN  1134
92 EWR    GSO  1120
93 JFK    MSP  1095
94 EWR    MKE  1094
95 EWR    SJU  1067
96 LGA    PIT  1067
97 LGA    MSY  1011

In [34]:
#3rd one

carrier_performance <- flights %>%
  group_by(carrier) %>%
  summarize(
    total_flights = n(),
    average_delay = mean(arr_delay, na.rm = TRUE),
    on_time_arrival_rate = mean(arr_delay <= 15, na.rm = TRUE),
    average_distance = mean(distance, na.rm = TRUE)
  ) %>%
  arrange(desc(on_time_arrival_rate))

In [36]:
print("Solution for Exercise 3:")
print(carrier_performance)

[1] "Solution for Exercise 3:"
# A tibble: 16 × 5
   carrier total_flights average_delay on_time_arrival_rate average_distance
   <chr>           <int>         <dbl>                <dbl>            <dbl>
 1 HA                342        -6.92                 0.874            4983
 2 AS                714        -9.93                 0.856            2402
 3 US              20536         2.13                 0.821             553.
 4 VX               5162         1.76                 0.819            2499.
 5 DL              48110         1.64                 0.818            1237.
 6 AA              32729         0.364                0.812            1340.
 7 UA              58665         3.56                 0.782            1529.
 8 OO                 32        11.9                  0.759             501.
 9 WN              12275         9.65                 0.751             996.
10 9E              18460         7.38                 0.751             530.
11 B6              54635         9.46                 0.739            1069.
12 MQ              26397        10.8                  0.729             570.
13 EV              54173        15.8                  0.686             563.
14 YV                601        15.6                  0.686             375.
15 FL               3260        20.1                  0.665             665.
16 F9                685        21.9                  0.627            1620

In [37]:

#4th one

monthly_trends <- flights %>%
  mutate(peak_season = ifelse(month %in% 6:8, "peak", "not_peak")) %>%
  group_by(month, peak_season) %>%
  summarize(
    total_flights = n(),
    average_distance = mean(distance, na.rm = TRUE),
    cancellation_rate = mean(is.na(dep_time)),
    average_delay = mean(arr_delay, na.rm = TRUE)
  )

`summarise()` has grouped output by 'month'. You can override using the
`.groups` argument.

In [39]:
print("The answer for this is")
print(monthly_trends)

[1] "The answer for this is"
# A tibble: 12 × 6
# Groups:   month [12]
   month peak_season total_flights average_distance cancellation_rate
   <int> <chr>               <int>            <dbl>             <dbl>
 1     1 not_peak            27004            1007.           0.0193
 2     2 not_peak            24951            1001.           0.0505
 3     3 not_peak            28834            1012.           0.0299
 4     4 not_peak            28330            1039.           0.0236
 5     5 not_peak            28796            1041.           0.0196
 6     6 peak                28243            1057.           0.0357
 7     7 peak                29425            1059.           0.0319
 8     8 peak                29327            1062.           0.0166
 9     9 not_peak            27574            1041.           0.0164
10    10 not_peak            28889            1039.           0.00817
11    11 not_peak            27268            1050.           0.00854
12    12 not_peak            28135            1065.           0.0364
# ℹ 1 more variable: average_delay <dbl>

In [40]:
#5th one

revenue_analysis <- flights %>%
  mutate(
    estimated_price = case_when(
      distance < 500 ~ 150,
      distance >= 500 & distance <= 1000 ~ 250,
      distance > 1000 ~ 400
    ),
    peak_season_premium = ifelse(month %in% 6:8, 1.20, 1),
    estimated_revenue = estimated_price * peak_season_premium
  ) %>%
  group_by(carrier) %>%
  summarize(
    total_revenue = sum(estimated_revenue, na.rm = TRUE)
  ) %>%
  arrange(desc(total_revenue))

In [41]:

print("Solution for Exercise 5:")
print(revenue_analysis)

[1] "Solution for Exercise 5:"
# A tibble: 16 × 2
   carrier total_revenue
   <chr>           <dbl>
 1 UA           21366470
 2 B6           17586180
 3 DL           16894520
 4 EV           12644490
 5 AA           12170810
 6 MQ            5967130
 7 US            4744760
 8 9E            4329600
 9 WN            3812010
10 VX            2181440
11 FL             762520
12 AS             300320
13 F9             287440
14 HA             144160
15 YV             126620
16 OO               6080

In [42]:
#6th one

market_competition <- flights %>%
  group_by(origin, dest) %>%
  summarize(
    num_carriers = n_distinct(carrier),
    carrier_market_share = prop.table(table(carrier)),
    avg_price = mean(distance), # Placeholder, needs refinement
    on_time_performance = mean(arr_delay <= 15, na.rm = TRUE)
  ) %>%
  filter(num_carriers >= 3) %>%
  mutate(monopoly = ifelse(max(carrier_market_share) > 0.8, "Yes", "No"))

print("Solution for Exercise 6:")
market_competition

Warning message:
“Returning more (or less) than 1 row per `summarise()` group was deprecated in
dplyr 1.1.0.
ℹ Please use `reframe()` instead.
ℹ When switching from `summarise()` to `reframe()`, remember that `reframe()`
  always returns an ungrouped data frame and adjust accordingly.”
`summarise()` has grouped output by 'origin', 'dest'. You can override using
the `.groups` argument.

[1] "Solution for Exercise 6:"

    origin dest num_carriers carrier_market_share <NA>         avg_price
1   EWR    ATL  4            9E                   0.0007964954  746
2   EWR    ATL  4            DL                   0.6278375149  746
3   EWR    ATL  4            EV                   0.3508562326  746
4   EWR    ATL  4            UA                   0.0205097571  746
5   EWR    BOS  3            B6                   0.3427820537  200
6   EWR    BOS  3            EV                   0.0298479444  200
7   EWR    BOS  3            UA                   0.6273700019  200
8   EWR    CLT  3            EV                   0.3565459610  529
9   EWR    CLT  3            UA                   0.0003979308  529
10  EWR    CLT  3            US                   0.6430561082  529
11  EWR    DTW  5            9E                   0.0726872247  488
12  EWR    DTW  5            DL                   0.1305852738  488
13  EWR    DTW  5            EV                   0.7957835116  488
14  EWR    DTW  5            OO                   0.0006293266  488
15  EWR    DTW  5            UA                   0.0003146633  488
16  EWR    LAX  3            AA                   0.0743078176 2454
17  EWR    LAX  3            UA                   0.7662866450 2454
18  EWR    LAX  3            VX                   0.1594055375 2454
19  EWR    MSP  5            9E                   0.0748843080 1008
20  EWR    MSP  5            DL                   0.1766933109 1008
21  EWR    MSP  5            EV                   0.7458981910 1008
22  EWR    MSP  5            OO                   0.0016827934 1008
23  EWR    MSP  5            UA                   0.0008413967 1008
24  EWR    MSY  3            EV                   0.5090909091 1167
25  EWR    MSY  3            UA                   0.2329004329 1167
26  EWR    MSY  3            WN                   0.2580086580 1167
27  EWR    ORD  3            EV                   0.0003278689  719
28  EWR    ORD  3            MQ                   0.3731147541  719
29  EWR    ORD  3            UA                   0.6265573770  719
30  EWR    PHX  3            UA                   0.4113110540 2133
⋮   ⋮      ⋮    ⋮            ⋮                    ⋮            ⋮
174 LGA    MSP  3            9E                   0.0002693240 1020
175 LGA    MSP  3            DL                   0.6514947482 1020
176 LGA    MSP  3            MQ                   0.3482359278 1020
177 LGA    MSY  3            9E                   0.0009891197 1183
178 LGA    MSY  3            DL                   0.9970326409 1183
179 LGA    MSY  3            EV                   0.0019782394 1183
180 LGA    ORD  3            AA                   0.6428813368  733
181 LGA    ORD  3            OO                   0.0001129050  733
182 LGA    ORD  3            UA                   0.3570057582  733
183 LGA    PBI  4            AA                   0.0332792208 1035
184 LGA    PBI  4            B6                   0.3693181818 1035
185 LGA    PBI  4            DL                   0.5949675325 1035
186 LGA    PBI  4            EV                   0.0024350649 1035
187 LGA    PIT  3            9E                   0.1087160262  335
188 LGA    PIT  3            DL                   0.1911902530  335
189 LGA    PIT  3            EV                   0.7000937207  335
190 LGA    RDU  3            9E                   0.0192683608  431
191 LGA    RDU  3            EV                   0.0497067858  431
192 LGA    RDU  3            MQ                   0.9310248534  431
193 LGA    RSW  3            9E                   0.0880420499 1080
194 LGA    RSW  3            B6                   0.4796320631 1080
195 LGA    RSW  3            DL                   0.4323258870 1080
196 LGA    SRQ  4            9E                   0.1058344640 1047
197 LGA    SRQ  4            B6                   0.4952510176 1047
198 LGA    SRQ  4            DL                   0.3595658073 1047
199 LGA    SRQ  4            EV                   0.0393487110 1047
200 LGA    STL  4            AA                   0.4950603732  888
201 LGA    STL  4            EV                   0.0016465423  888
202 LGA    STL  4            MQ                   0.0762897914  888
203 LGA    STL  4            WN                   0.4270032931  888
    on_time_performance monopoly
1   0.7387203           No
2   0.7387203           No
3   0.7387203           No
4   0.7387203           No
5   0.7983610           No
6   0.7983610           No
7   0.7983610           No
8   0.7666054           No
9   0.7666054           No
10  0.7666054           No
11  0.7357926           No
12  0.7357926           No
13  0.7357926           No
14  0.7357926           No
15  0.7357926           No
16  0.7729608           No
17  0.7729608           No
18  0.7729608           No
19  0.7649667           No
20  0.7649667           No
21  0.7649667           No
22  0.7649667           No
23  0.7649667           No
24  0.7306667           No
25  0.7306667           No
26  0.7306667           No
27  0.7498284           No
28  0.7498284           No
29  0.7498284           No
30  0.7854749           No
⋮   ⋮                   ⋮
174 0.7812155           No
175 0.7812155           No
176 0.7812155           No
177 0.8116232           Yes
178 0.8116232           Yes
179 0.8116232           Yes
180 0.7960503           No
181 0.7960503           No
182 0.7960503           No
183 0.7694524           No
184 0.7694524           No
185 0.7694524           No
186 0.7694524           No
187 0.7341897           No
188 0.7341897           No
189 0.7341897           No
190 0.7489614           Yes
191 0.7489614           Yes
192 0.7489614           Yes
193 0.7606383           No
194 0.7606383           No
195 0.7606383           No
196 0.7846365           No
197 0.7846365           No
198 0.7846365           No
199 0.7846365           No
200 0.7945671           No
201 0.7945671           No
202 0.7945671           No
203 0.7945671           No